apiVersion: v1
kind: Service
metadata:
  name: ip2country
  labels:
    run: ip2country
spec:
  ports:
  - name: ssh
    port: 22
    protocol: TCP
  - name: ip2contry-service
    port: 8033
  selector:
    app: harbor-ip2country
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harbor-ip2country-deployment
  labels:
    app: harbor-ip2country
spec:
  selector:
    matchLabels:
      app: harbor-ip2country
  template:
    metadata:
      labels:
        app: harbor-ip2country
    spec:
      containers:
      - name: harbor-ip2country
        image: reg.tiertime.net/harbor/harbor_ip2country:v1.0 
