shadowsocks:
  image: shadowsocks/shadowsocks-libev
  ports:
    - "8388:8388/tcp"
    - "8388:8388/udp"
  environment:
    - METHOD=xchacha20-ietf-poly1305
    - PASSWORD=1qaz2wsx
  restart: unless-stopped
